fix issue Credential was deleted due to "Failed to update online status" #217
IBM/cloud-operators pull request #226
Opened 2020-10-13 05:47 UTC by qibobo

2020-10-22 02:00 UTC, qibobo commented
@JohnStarich any comment?

2020-10-27 01:43 UTC, JohnStarich commented
@qibobo Sorry for the delay. FYI I've fixed up the CI tests, so now we'll need them green to merge.

I'll try and find some time to review your changes soon!

2020-10-28 21:32 UTC, JohnStarich requested changes

2020-10-28 21:32 UTC, JohnStarich commented on controllers/binding_controller.go
> +		return ctrl.Result{Requeue: true}, nil
The switch to retries looks good 👍 
Let's also return the error here
```suggestion
		return ctrl.Result{Requeue: true}, err
```

2020-10-30 06:20 UTC, qibobo commented
@JohnStarich Done. Thank you.

2020-11-02 23:56 UTC, JohnStarich reviewed
Code changes look ok 👍 
Please fix the issues reported in Travis, then we can merge

2020-11-04 12:30 UTC, qibobo commented
@JohnStarich Fixed the UT, why the codecov is failed?

2020-11-06 00:20 UTC, JohnStarich approved these changes
Looks great, thanks @qibobo! 🎉 

Integration tests passed locally too. ✅

2020-11-06 00:21 UTC, merged